### PR TITLE
Switch to new theme and update VuePress to beta49

### PR DESCRIPTION
**Pull request by lifehackerhansol**
Non-breaking changes in the guide:
- URLs in the get-started version table now explicitly include `.html` as otherwise it doesn't work under Vite. (It probably works under GitHub Pages, but it's better for it to work everywhere instead)

Breaking changes in the guide:
- The front page button is nixed and replaced with a link to get-started at end of page

This was tested and working under Vite, but not tested under GitHub Actions; however, an example of this update can be seen at https://ios.cfw.guide as well as https://dsi.cfw.guide.

The breaking change can probably be restored, but I went the lazy route :P 

Some other minor cleanup was done in terms of unused code etc.

### CODE REVIEW

**Comment by emiyl** [comment]
thank you, unfortunately the Btn and BtnToggler components are used in several pages and this will break those components

**Comment by lifehackerhansol** [comment]
Would you be willing to point at an example? I genuinely cannot find where it is being used.

**Comment by lifehackerhansol** [comment]
Oh, I see now, it's for the hardware buttons, not actual website buttons

I'll take a look at it.

**Comment by lifehackerhansol** [comment]
@emiyl button toggler is restored. I tested it locally in the adrenaline page and the buttons show as expected.

**Comment by emiyl** [comment]
thank you!

**Comment by MattTheTekie** [comment]
@lifehackerhansol Awesome stuff!

**Pull request merged**
