### PR TITLE
Replace StorageMgr with YAMT

### PR DESCRIPTION
**Pull request by SCOTT0852**
StorageMgr is the buggiest SD2Vita plugin you can get your hands on, not to mention it delays boot time by 15 seconds. Hopefully a guide for YAMT stops people for blaming it on "bricking" their consoles when it really hasn't done anything like that. I also replaced the "Getting Started" links on the Linux and Mac SD formatting setup pages with the SD2Vita guide, as it doesn't make sense to go from the SD2Vita guide to the SD formatting page and then all the way back to Getting Started.

### CODE REVIEW

**Comment by Plailect** [comment]
Sure it's faster / more stable, but is this really a replacement for people who actually use the configs that StorageMgr provides that YAMT doesn't?

**Comment by Cimmerian-Iter** [comment]
Personnally i wouldn't.
YAMT has it's own bag of problems as well as corruption (caused by the settings app when saving the config.) Rin has already experienced it.

Storagemgr delay the boot by 10-15 second but is it a problem? the advantage of storagemgr is that it creates a log (hence why it also boot longer) which is useful for us helpers to debug why the sd2vita doesn't works. 

And "buggiest" would be false, it does its job well and i never seen any complain about it.

**Comment by SCOTT0852** [comment]
I'm going to try and rewrite this since yamt's bugs have been fixed, what I wrote is outdated now anyway. (the storagemgr page won't be removed in the rewrite since yamt requires enso and occasionally an sd card won't work with yamt)

**Comment by Cimmerian-Iter** [comment]
yeah the new version of yamt outclass storagemgr and even have an in built format option so no need for a pc anymore. But we still need to keep storagemgr guide just in case since skg said that some chinese microsd won't be recognized by sony driver (while storagemgr can recognize them) Don't think it's really that important but worth mentioning

**Pull request closed without merging**
